// =============================================================================
// FILE: 02-typescript-fundamentals/utility-types.ts
// TOPIC: Built-in Utility Types (Type Transformations)
// =============================================================================

// Standard base interface for demonstrating transformations:
interface Task {
  id: number;
  title: string;
  description: string;
  isCompleted: boolean;
  priority: "low" | "medium" | "high";
}

// -----------------------------------------------------------------------------
// 1. PARTIAL<T>
// -----------------------------------------------------------------------------
// Constructs a type with all properties of T set to optional (?).
// Perfect for update/patch request bodies.

type UpdateTaskDto = Partial<Task>;

const taskUpdate: UpdateTaskDto = {
  isCompleted: true, // All other properties can be omitted
};

// -----------------------------------------------------------------------------
// 2. REQUIRED<T>
// -----------------------------------------------------------------------------
// Constructs a type with all properties of T set to required (removes ?).

interface OptionalUser {
  id: number;
  name?: string;
}

type DefiniteUser = Required<OptionalUser>;
// Must include both id AND name:
const fullUser: DefiniteUser = { id: 1, name: "Carl" };

// -----------------------------------------------------------------------------
// 3. READONLY<T>
// -----------------------------------------------------------------------------
// Constructs a type with all properties of T set to readonly.

type ImmutableTask = Readonly<Task>;

const lockedTask: ImmutableTask = {
  id: 1,
  title: "Setup Database",
  description: "Configure PostgreSQL connection",
  isCompleted: true,
  priority: "high",
};
// lockedTask.title = "New Title"; // Error: Cannot assign to 'title' because it is a read-only property.

// -----------------------------------------------------------------------------
// 4. PICK<T, KEYS>
// -----------------------------------------------------------------------------
// Constructs a type by choosing only the specified keys from T.

type TaskSummary = Pick<Task, "id" | "title">;

const summary: TaskSummary = {
  id: 101,
  title: "Write documentation",
};

// -----------------------------------------------------------------------------
// 5. OMIT<T, KEYS>
// -----------------------------------------------------------------------------
// Constructs a type by picking all properties from T and removing specified keys.

type NewTaskPayload = Omit<Task, "id">; // ID will be generated by database

const payload: NewTaskPayload = {
  title: "Deploy API",
  description: "Deploy server to production cluster",
  isCompleted: false,
  priority: "high",
};

// -----------------------------------------------------------------------------
// 6. RECORD<KEYS, TYPE>
// -----------------------------------------------------------------------------
// Constructs an object type whose property keys are KEYS and values are TYPE.

type Role = "admin" | "manager" | "customer";

type RolePermissions = Record<Role, string[]>;

const permissions: RolePermissions = {
  admin: ["read", "write", "delete"],
  manager: ["read", "write"],
  customer: ["read"],
};

// -----------------------------------------------------------------------------
// 7. EXCLUDE<UNIONTYPE, EXCLUDEDMEMBERS> & EXTRACT<TYPE, UNION>
// -----------------------------------------------------------------------------
type Status = "draft" | "review" | "published" | "archived";

type ActiveStatus = Exclude<Status, "archived">; // "draft" | "review" | "published"
type FinalStatus = Extract<Status, "published" | "archived">; // "published" | "archived"

// -----------------------------------------------------------------------------
// 8. NONNULLABLE<T>
// -----------------------------------------------------------------------------
// Excludes null and undefined from T.

type RawInput = string | number | null | undefined;
type ValidInput = NonNullable<RawInput>; // string | number