/*
  ==============================================================================
  W3SCHOOLS-STYLE LEARNING GUIDE: REST API Error Responses (RFC 7807 Standard)
  ==============================================================================

  1. WHAT ARE STANDARDIZED ERROR RESPONSES?
     In REST, error responses must be consistent, actionable, and machine-readable.
     RFC 7807 ("Problem Details for HTTP APIs") is the official IETF standard specification
     defining a standard JSON media type for HTTP error reporting:
     `application/problem+json`.

  2. REAL-LIFE ANALOGY:
     A Medical Diagnostic Report:
     - Bad error report: Doctor says "Something is wrong" (Vague, no code).
     - Good RFC 7807 report: Lists ICD Code (E11.9), Title ("Type 2 Diabetes"),
       Specific severity, and exact next treatment steps.

  3. JARGON BUSTER:
     - RFC 7807 Problem Details fields:
       - `type`: A URI reference that identifies the problem type documentation.
       - `title`: A short, human-readable summary of the problem type.
       - `status`: The HTTP status code generated by the origin server.
       - `detail`: A human-readable explanation specific to this occurrence.
       - `instance`: A URI reference that identifies the specific endpoint or trace ID.
       - `invalidParams`: Custom extension array listing specific field violations.
*/

// =============================================================================
// BAD PRACTICE: INCONSISTENT RAW ERROR RESPONSES
// =============================================================================
/*
  // DANGER: Leaking internal SQL errors or stack traces to clients:
  res.status(500).json({ error: "SELECT * FROM users WHERE id = syntax error at..." });
  // Hackers love this! It exposes your database schema and library versions!
*/

// =============================================================================
// GOOD PRACTICE: RFC 7807 "PROBLEM DETAILS" IMPLEMENTATION
// =============================================================================

interface ProblemDetails {
  type: string;
  title: string;
  status: number;
  detail: string;
  instance: string;
  invalidParams?: Array<{ name: string; reason: string }>;
}

class ProblemDetailsFactory {
  // 400 Bad Request / Validation Failure
  public static validationError(
    instanceUri: string,
    invalidFields: Array<{ name: string; reason: string }>
  ): ProblemDetails {
    return {
      type: "https://api.taskflow.dev/errors/validation-error",
      title: "Your request parameters failed validation.",
      status: 400,
      detail: "One or more fields in your request payload do not satisfy constraints.",
      instance: instanceUri,
      invalidParams: invalidFields,
    };
  }

  // 404 Not Found
  public static notFoundError(instanceUri: string, resourceName: string, id: string): ProblemDetails {
    return {
      type: "https://api.taskflow.dev/errors/resource-not-found",
      title: "Resource Not Found",
      status: 404,
      detail: `The requested ${resourceName} with identifier '${id}' does not exist on this server.`,
      instance: instanceUri,
    };
  }

  // 409 Conflict
  public static conflictError(instanceUri: string, reason: string): ProblemDetails {
    return {
      type: "https://api.taskflow.dev/errors/resource-conflict",
      title: "Resource State Conflict",
      status: 409,
      detail: reason,
      instance: instanceUri,
    };
  }
}

console.log("=== RFC 7807 Error 1: Validation Failure (HTTP 400) ===");
const valError = ProblemDetailsFactory.validationError("/api/v1/tasks", [
  { name: "title", reason: "Title cannot be empty." },
  { name: "priority", reason: "Value must be low, medium, or high." },
]);
console.log(JSON.stringify(valError, null, 2));

console.log("\n=== RFC 7807 Error 2: Resource Not Found (HTTP 404) ===");
const notFound = ProblemDetailsFactory.notFoundError("/api/v1/tasks/tsk_99", "Task", "tsk_99");
console.log(JSON.stringify(notFound, null, 2));

/*
  ------------------------------------------------------------------------------
  [EXPECTED OUTPUT IN TERMINAL]
  ------------------------------------------------------------------------------
  === RFC 7807 Error 1: Validation Failure (HTTP 400) ===
  {
    "type": "https://api.taskflow.dev/errors/validation-error",
    "title": "Your request parameters failed validation.",
    "status": 400,
    "detail": "One or more fields in your request payload do not satisfy constraints.",
    "instance": "/api/v1/tasks",
    "invalidParams": [
      {
        "name": "title",
        "reason": "Title cannot be empty."
      },
      {
        "name": "priority",
        "reason": "Value must be low, medium, or high."
      }
    ]
  }

  === RFC 7807 Error 2: Resource Not Found (HTTP 404) ===
  {
    "type": "https://api.taskflow.dev/errors/resource-not-found",
    "title": "Resource Not Found",
    "status": 404,
    "detail": "The requested Task with identifier 'tsk_99' does not exist on this server.",
    "instance": "/api/v1/tasks/tsk_99"
  }
*/

// =============================================================================
// BEHIND THE SCENES: KEY HEADERS FOR RFC 7807
// =============================================================================
/*
  When returning RFC 7807 errors:
  - Header: `Content-Type: application/problem+json`
  - Never include internal stack traces or database connection strings in production!
  - Always provide a unique `instance` path or trace request ID (e.g. `req_abc123`)
    so users can quote it to customer support to look up the server log.
*/